name: Docker Compose CI (Post-Merge Dev)

on:
  push:
    branches: [ dev ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and Start All Services
        run: |
          docker compose up -d --build
          docker compose ps

      - name: Wait for Services to Become Healthy
        run: |
          echo "Waiting for services to be healthy..."
          for i in {1..30}; do
            if curl -sf http://localhost:8081/actuator/health &&
               curl -sf http://localhost:8082/actuator/health &&
               curl -sf http://localhost:8083/actuator/health &&
               curl -f http://localhost:4200/home; then
              echo "All services are healthy"
              exit 0
            fi
            echo "Not ready yet... retrying"
            sleep 5
          done

          echo "Services did not become healthy in time"
          docker compose logs
          exit 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install  dependencies
        working-directory: playwright-tests
        run: npm ci

      #I removed playwright browsers from here as api don't need that

      - name: Run Playwright tests
        working-directory: playwright-tests
        run: npx playwright test src/tests/ui/api

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-tests/playwright-report/
          retention-days: 30

      - name: Tear Down Containers
        if: always()
        run: |
          docker compose down --remove-orphans -v
